site_name: Wink
pages:
    - Overview: index.md
    - Getting Started: [install.md,use.md]
    - Fundamentals: [introduction.md,howwork.md]
    - Help& Community:
        - FAQ : faq.md
        - StackOverFlow: "https://stackoverflow.com/questions/tagged/wink-build?sort=active"
    - Change Log: changelog.md

theme:
  name: material
  logo: 'images/wink.svg'
  favicon: 'images/favicon.png'
  palette:
      primary: "black"
      accent: "Light"